/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    customers: CustomerAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    artists: Artist;
    categories: Category;
    orders: Order;
    'custom-requests': CustomRequest;
    pages: Page;
    media: Media;
    'garment-types': GarmentType;
    discounts: Discount;
    payments: Payment;
    customers: Customer;
    carts: Cart;
    'rate-limit-counters': RateLimitCounter;
    'idempotency-keys': IdempotencyKey;
    'audit-log': AuditLog;
    'analytics-counters': AnalyticsCounter;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    artists: ArtistsSelect<false> | ArtistsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'custom-requests': CustomRequestsSelect<false> | CustomRequestsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'garment-types': GarmentTypesSelect<false> | GarmentTypesSelect<true>;
    discounts: DiscountsSelect<false> | DiscountsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    'rate-limit-counters': RateLimitCountersSelect<false> | RateLimitCountersSelect<true>;
    'idempotency-keys': IdempotencyKeysSelect<false> | IdempotencyKeysSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'analytics-counters': AnalyticsCountersSelect<false> | AnalyticsCountersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ar') | ('en' | 'ar')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    homepage: Homepage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: 'en' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Customer | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Auto-generated from the title if left empty; always normalized to lowercase-kebab-case.
   */
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Price in USD
   */
  price: number;
  images?:
    | {
        /**
         * Pick from the Media library or upload a new image. Fills the URL below automatically on save.
         */
        image?: (number | null) | Media;
        /**
         * Auto-filled from the image above. You can also paste a Supabase Storage public URL directly.
         */
        url?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  artist?: (number | null) | Artist;
  category?: (number | null) | Category;
  /**
   * Powers the "More like this" suggestions on the product page. Managed under Collections → Garment Types.
   */
  garmentType?: (number | null) | GarmentType;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Sized stock for production pieces (S / M / L / XL…). When any sizes are added, customers must pick one and stock is tracked per size. Leave empty for one-of-a-kind or unsized pieces — the single Stock Quantity below is used instead.
   */
  sizes?:
    | {
        /**
         * e.g. S, M, L, XL, Oversized
         */
        label: string;
        stockQuantity: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Used when no sizes are configured above (one-of-a-kind / unsized pieces).
   */
  stockQuantity: number;
  /**
   * Single unique piece — removes from catalog when sold
   */
  isOneOfAKind?: boolean | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload images here, then choose them on products, artists, and page sections. Files are stored in Supabase Storage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and SEO (e.g. "Hand-painted hoodie, front view").
   */
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists".
 */
export interface Artist {
  id: number;
  name: string;
  /**
   * Auto-generated from the name if left empty, e.g. "fairouz" or "mashrou-leila"
   */
  slug: string;
  bio?: string | null;
  genre?: string | null;
  /**
   * Pick from the Media library or upload a photo. Fills the URL below automatically on save.
   */
  photoMedia?: (number | null) | Media;
  /**
   * Auto-filled from the photo above. You can also paste a Supabase Storage public URL directly.
   */
  photo?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Auto-generated from the name if left empty.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Garment options shown on the Custom Request form. Drag rows to set the order they appear in the dropdown.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "garment-types".
 */
export interface GarmentType {
  id: number;
  _order?: string | null;
  /**
   * e.g. Hoodie, T-Shirt, Jacket, Tote Bag
   */
  name: string;
  /**
   * Auto-generated from the name if left empty.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  customerName: string;
  customerPhone: string;
  customerEmail?: string | null;
  /**
   * Linked customer account — guest orders have none.
   */
  customer?: (number | null) | Customer;
  deliveryAddress: string;
  /**
   * Lebanon area / city (e.g. Beirut, Tripoli, Saida)
   */
  area: string;
  items: {
    productId: string;
    titleAtPurchase: string;
    /**
     * Chosen size — empty for unsized/one-of-a-kind pieces
     */
    size?: string | null;
    priceAtPurchase: number;
    quantity: number;
    imageUrl?: string | null;
    id?: string | null;
  }[];
  subtotal: number;
  deliveryFee: number;
  /**
   * Discount code applied at checkout (if any).
   */
  discountCode?: string | null;
  /**
   * Amount taken off the subtotal by the discount code.
   */
  discountAmount?: number | null;
  total: number;
  paymentMethod: 'cod' | 'bank_transfer' | 'card' | 'omt';
  paymentStatus?:
    ('pending' | 'awaiting_payment' | 'paid' | 'failed' | 'expired' | 'refunded' | 'partially_refunded') | null;
  /**
   * Online-payment orders only. Stock is released and the order cancelled if payment isn't confirmed by this time (ROADMAP F1 §2.1).
   */
  paymentExpiresAt?: string | null;
  /**
   * LBP-per-USD rate at the moment of purchase, snapshotted from Site Settings — USD stays the money of record.
   */
  exchangeRateAtPurchase?: number | null;
  /**
   * How much of this order has been refunded so far (ROADMAP F2 §2.6). Updated only by the admin refund action.
   */
  refundedAmount?: number | null;
  orderStatus: 'pending' | 'confirmed' | 'in_production' | 'shipped' | 'delivered' | 'cancelled';
  /**
   * Customer notes
   */
  notes?: string | null;
  /**
   * Courier handling this delivery, e.g. "Wakilni" or "Toters" — manual entry (ROADMAP Part 3.2 v1; no real courier API integrated yet). Shown to the customer once set.
   */
  courierName?: string | null;
  /**
   * Courier's tracking reference/number, if they provide one.
   */
  trackingRef?: string | null;
  dispatchDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name: string;
  phone?: string | null;
  /**
   * Saved delivery addresses — offered at checkout.
   */
  addresses?:
    | {
        /**
         * e.g. Home, Work
         */
        label?: string | null;
        area?: string | null;
        deliveryAddress?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Saved-for-later products.
   */
  wishlist?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-requests".
 */
export interface CustomRequest {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  /**
   * What does the customer want painted?
   */
  description: string;
  /**
   * Artist or band they want referenced
   */
  referenceArtist?: string | null;
  referenceSong?: string | null;
  /**
   * Managed under Collections → Garment Types.
   */
  garmentType?: (number | null) | GarmentType;
  status?: ('new' | 'reviewing' | 'quoted' | 'accepted' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Auto-generated from the title if left empty — e.g. "about", "faq", "artist-fairouz"
   */
  slug: string;
  /**
   * Draft pages are hidden from the storefront and the sitemap. Set to Published to make the page live.
   */
  status: 'draft' | 'published';
  /**
   * Simple text content. Ignored when "Sections" below has visible blocks — build a full landing page there instead.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Build this page from full-width sections (same blocks as the homepage). When any section is visible here, it replaces the simple text content above.
   */
  sections?:
    | (
        | {
            /**
             * Small label above headline, e.g. "Lebanon · Hand-painted"
             */
            eyebrow?: string | null;
            headline?: string | null;
            subline?: string | null;
            /**
             * Primary button text, e.g. "Shop Now"
             */
            ctaLabel?: string | null;
            /**
             * Primary button link, e.g. /shop
             */
            ctaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            /**
             * Pick or upload a full-bleed background image. Fills the URL below.
             */
            bgImageMedia?: (number | null) | Media;
            /**
             * Auto-filled from the image above, or paste a Supabase Storage public URL.
             */
            bgImage?: string | null;
            /**
             * Hex background color, e.g. #0a0a0a (shown behind/instead of image)
             */
            bgColor?: string | null;
            /**
             * Black overlay over bg image 0–100 (use 30–60 to ensure text is readable)
             */
            overlayOpacity?: number | null;
            textAlign?: ('left' | 'center' | 'right') | null;
            minHeight?: ('50vh' | '70vh' | '80vh' | '100vh') | null;
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Each slide is a full-screen panel. Add at least one.
             */
            slides?:
              | {
                  /**
                   * Pick or upload a slide background. Fills the URL below.
                   */
                  bgImageMedia?: (number | null) | Media;
                  /**
                   * Auto-filled from the image above, or paste a Supabase Storage public URL.
                   */
                  bgImage?: string | null;
                  /**
                   * Hex fallback color shown behind/instead of image
                   */
                  bgColor?: string | null;
                  /**
                   * Black overlay 0–100 for text legibility
                   */
                  overlayOpacity?: number | null;
                  eyebrow?: string | null;
                  headline?: string | null;
                  subline?: string | null;
                  ctaLabel?: string | null;
                  ctaHref?: string | null;
                  id?: string | null;
                }[]
              | null;
            height?: ('60vh' | '70vh' | '80vh' | '100vh') | null;
            /**
             * Milliseconds between auto-advance (default: 5000 = 5s). Set to 0 to disable.
             */
            autoplayInterval?: number | null;
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'slideshow';
          }
        | {
            sectionTitle?: string | null;
            viewAllLabel?: string | null;
            viewAllHref?: string | null;
            source?: ('latest' | 'manual') | null;
            /**
             * How many products to show
             */
            limit?: number | null;
            /**
             * Pick the exact products to feature
             */
            products?: (number | Product)[] | null;
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featured-products';
          }
        | {
            /**
             * Pick or upload the section image. Fills the URL below.
             */
            imageMedia?: (number | null) | Media;
            /**
             * Auto-filled from the image above, or paste a Supabase Storage public URL.
             */
            image?: string | null;
            imageAlt?: string | null;
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            imagePosition?: ('left' | 'right') | null;
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-text';
          }
        | {
            /**
             * A single impactful sentence — displayed centered in large muted text.
             */
            text: string;
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statement';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text';
          }
        | {
            headline?: string | null;
            subline?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            /**
             * Pick or upload an optional full-bleed background. Fills the URL below.
             */
            bgImageMedia?: (number | null) | Media;
            /**
             * Auto-filled from the image above, or paste a Supabase Storage public URL.
             */
            bgImage?: string | null;
            /**
             * Hex background color, e.g. #e8d5b0. Defaults to accent color.
             */
            bgColor?: string | null;
            overlayOpacity?: number | null;
            /**
             * Hex text color. Defaults to on-accent (auto from theme).
             */
            textColor?: string | null;
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta-banner';
          }
      )[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Supabase Storage URL — copy the public URL from the Supabase Storage dashboard
     */
    ogImage?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discounts".
 */
export interface Discount {
  id: number;
  /**
   * What the customer types at checkout. Case-insensitive — stored uppercase.
   */
  code: string;
  type: 'percentage' | 'fixed';
  /**
   * For percentage: 0–100. For fixed: the dollar amount off the subtotal.
   */
  value: number;
  /**
   * Uncheck to disable the code without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Minimum cart subtotal (USD) required to use this code. Leave empty for none.
   */
  minSubtotal?: number | null;
  /**
   * Optional expiry. The code stops working after this date/time.
   */
  expiresAt?: string | null;
  /**
   * Max total redemptions across all customers. Leave empty (or 0) for unlimited.
   */
  usageLimit?: number | null;
  /**
   * How many times this code has been used. Updated automatically.
   */
  usageCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Payment attempts against orders. Created and updated only by the checkout/webhook flow.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  order: number | Order;
  /**
   * New vendors (Areeba, NetCommerce, …) get added here as their adapters ship.
   */
  provider: 'mock' | 'omt';
  /**
   * The provider's own reference for this attempt.
   */
  providerRef: string;
  amount: number;
  currency: string;
  status: 'initiated' | 'pending' | 'paid' | 'failed' | 'expired' | 'refunded' | 'partially_refunded';
  /**
   * Raw webhook payloads received for this payment (audit trail).
   */
  rawEvents?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  /**
   * Guest session id (from the cart-session cookie). Empty once claimed by an account.
   */
  sessionId?: string | null;
  customer?: (number | null) | Customer;
  items?:
    | {
        product: number | Product;
        size?: string | null;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-limit-counters".
 */
export interface RateLimitCounter {
  id: number;
  key: string;
  count: number;
  windowStart: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "idempotency-keys".
 */
export interface IdempotencyKey {
  id: number;
  key: string;
  responseStatus: number;
  responseBody:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  collectionSlug: string;
  /**
   * Empty for globals (e.g. Site Settings).
   */
  documentId?: string | null;
  action: 'create' | 'update' | 'delete';
  /**
   * Snapshot of the admin's email — survives if that user account is later deleted.
   */
  userEmail: string;
  /**
   * One-line human-readable description.
   */
  summary: string;
  /**
   * Field names that changed (update) or the full new state (create).
   */
  changedFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-counters".
 */
export interface AnalyticsCounter {
  id: number;
  /**
   * YYYY-MM-DD (UTC)
   */
  date: string;
  pageViews: number;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'artists';
        value: number | Artist;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'custom-requests';
        value: number | CustomRequest;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'garment-types';
        value: number | GarmentType;
      } | null)
    | ({
        relationTo: 'discounts';
        value: number | Discount;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'rate-limit-counters';
        value: number | RateLimitCounter;
      } | null)
    | ({
        relationTo: 'idempotency-keys';
        value: number | IdempotencyKey;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'analytics-counters';
        value: number | AnalyticsCounter;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'customers';
        value: number | Customer;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'customers';
        value: number | Customer;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  price?: T;
  images?:
    | T
    | {
        image?: T;
        url?: T;
        alt?: T;
        id?: T;
      };
  artist?: T;
  category?: T;
  garmentType?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  sizes?:
    | T
    | {
        label?: T;
        stockQuantity?: T;
        id?: T;
      };
  stockQuantity?: T;
  isOneOfAKind?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists_select".
 */
export interface ArtistsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  genre?: T;
  photoMedia?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customerName?: T;
  customerPhone?: T;
  customerEmail?: T;
  customer?: T;
  deliveryAddress?: T;
  area?: T;
  items?:
    | T
    | {
        productId?: T;
        titleAtPurchase?: T;
        size?: T;
        priceAtPurchase?: T;
        quantity?: T;
        imageUrl?: T;
        id?: T;
      };
  subtotal?: T;
  deliveryFee?: T;
  discountCode?: T;
  discountAmount?: T;
  total?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  paymentExpiresAt?: T;
  exchangeRateAtPurchase?: T;
  refundedAmount?: T;
  orderStatus?: T;
  notes?: T;
  courierName?: T;
  trackingRef?: T;
  dispatchDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-requests_select".
 */
export interface CustomRequestsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  description?: T;
  referenceArtist?: T;
  referenceSong?: T;
  garmentType?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  content?: T;
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subline?: T;
              ctaLabel?: T;
              ctaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              bgImageMedia?: T;
              bgImage?: T;
              bgColor?: T;
              overlayOpacity?: T;
              textAlign?: T;
              minHeight?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        slideshow?:
          | T
          | {
              slides?:
                | T
                | {
                    bgImageMedia?: T;
                    bgImage?: T;
                    bgColor?: T;
                    overlayOpacity?: T;
                    eyebrow?: T;
                    headline?: T;
                    subline?: T;
                    ctaLabel?: T;
                    ctaHref?: T;
                    id?: T;
                  };
              height?: T;
              autoplayInterval?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        'featured-products'?:
          | T
          | {
              sectionTitle?: T;
              viewAllLabel?: T;
              viewAllHref?: T;
              source?: T;
              limit?: T;
              products?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        'image-text'?:
          | T
          | {
              imageMedia?: T;
              image?: T;
              imageAlt?: T;
              eyebrow?: T;
              heading?: T;
              body?: T;
              ctaLabel?: T;
              ctaHref?: T;
              imagePosition?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        statement?:
          | T
          | {
              text?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              content?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        'cta-banner'?:
          | T
          | {
              headline?: T;
              subline?: T;
              ctaLabel?: T;
              ctaHref?: T;
              bgImageMedia?: T;
              bgImage?: T;
              bgColor?: T;
              overlayOpacity?: T;
              textColor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "garment-types_select".
 */
export interface GarmentTypesSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discounts_select".
 */
export interface DiscountsSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  value?: T;
  enabled?: T;
  minSubtotal?: T;
  expiresAt?: T;
  usageLimit?: T;
  usageCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  order?: T;
  provider?: T;
  providerRef?: T;
  amount?: T;
  currency?: T;
  status?: T;
  rawEvents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  addresses?:
    | T
    | {
        label?: T;
        area?: T;
        deliveryAddress?: T;
        id?: T;
      };
  wishlist?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  sessionId?: T;
  customer?: T;
  items?:
    | T
    | {
        product?: T;
        size?: T;
        quantity?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-limit-counters_select".
 */
export interface RateLimitCountersSelect<T extends boolean = true> {
  key?: T;
  count?: T;
  windowStart?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "idempotency-keys_select".
 */
export interface IdempotencyKeysSelect<T extends boolean = true> {
  key?: T;
  responseStatus?: T;
  responseBody?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  collectionSlug?: T;
  documentId?: T;
  action?: T;
  userEmail?: T;
  summary?: T;
  changedFields?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-counters_select".
 */
export interface AnalyticsCountersSelect<T extends boolean = true> {
  date?: T;
  pageViews?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global brand settings — store name, colors, announcement bar, footer text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Displayed in the nav, footer, email subjects, and page titles.
   */
  storeName?: string | null;
  /**
   * Pick or upload a logo. Fills the URL below automatically. Leave blank to use the text logo.
   */
  logo?: (number | null) | Media;
  /**
   * Auto-filled from the logo above, or paste a Supabase Storage public URL. Leave blank to use the text logo.
   */
  logoUrl?: string | null;
  /**
   * Appended to the homepage browser-tab / social-share title ("Store — tagline") and shown on the homepage when no sections are configured.
   */
  tagline?: string | null;
  /**
   * Reply-to address on all order emails; also shown in the footer.
   */
  contactEmail?: string | null;
  /**
   * Full number with country code, e.g. +96170123456
   */
  whatsappNumber?: string | null;
  /**
   * Delivery areas and their fees. When configured, checkout shows these as a dropdown and the fee is added to the total. Leave empty to keep free-text area entry with no fee.
   */
  deliveryZones?:
    | {
        /**
         * e.g. "Beirut", "Mount Lebanon", "Tripoli & North"
         */
        label: string;
        /**
         * Delivery fee in USD for this zone
         */
        fee: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Order subtotal (USD) at or above which delivery is free. Leave empty to disable.
   */
  freeDeliveryThreshold?: number | null;
  /**
   * Shown at checkout, on the order confirmation page, and in the confirmation email when the customer picks Bank Transfer — bank name, account/IBAN, and what to put as the transfer reference.
   */
  bankTransferInstructions?: string | null;
  /**
   * Show "Card" as a checkout payment option (ROADMAP F1). Only the testing "Mock" provider exists so far — real vendor adapters (Areeba/NetCommerce) plug into the same toggle once onboarded. Also requires the ONLINE_PAYMENTS_ENABLED=true environment variable to be set — this checkbox alone is not enough, on purpose (a deploy-time safety net independent of this settings panel).
   */
  cardPaymentsEnabled?: boolean | null;
  /**
   * The Mock provider simulates a payment session for local testing — it is disabled automatically in production unless ALLOW_MOCK_PAYMENTS=true is set.
   */
  cardPaymentProvider?: 'mock' | null;
  /**
   * Show "OMT (pay at branch)" as a checkout payment option (ROADMAP F2). v1 is voucher + manual confirm — no OMT merchant agreement exists yet, so staff confirm payments by hand from the admin dashboard's "OMT Payments" panel. Also requires the ONLINE_PAYMENTS_ENABLED=true environment variable to be set — this checkbox alone is not enough, on purpose (a deploy-time safety net independent of this settings panel).
   */
  omtPaymentEnabled?: boolean | null;
  /**
   * Shown at checkout and on the order confirmation page alongside the voucher code — e.g. "Pay at any OMT branch within 48 hours."
   */
  omtInstructions?: string | null;
  /**
   * USD stays the money of record everywhere (payments, discounts, reports). "Both" adds an LBP equivalent next to prices using the exchange rate below.
   */
  currencyDisplayMode?: ('usd_only' | 'both') | null;
  /**
   * LBP per 1 USD, e.g. 89000. Update this as the rate moves — each order snapshots the rate at purchase time, so past orders keep the rate they were placed under.
   */
  exchangeRate?: number | null;
  /**
   * Show VAT on invoices (ROADMAP Part 3.1). Prices are treated as VAT-inclusive — the VAT share is broken out on the invoice, never added on top. Off by default for unregistered small brands.
   */
  vatEnabled?: boolean | null;
  /**
   * VAT rate as a percentage. Lebanon standard rate is 11%.
   */
  vatRate?: number | null;
  /**
   * Shown on invoices under the brand details.
   */
  vatRegistrationNumber?: string | null;
  /**
   * Email a low-stock summary when any published product is at or below the threshold (ROADMAP Part 3.3). Pushes the dashboard's existing low-stock widget instead of relying on someone checking it.
   */
  lowStockAlertEnabled?: boolean | null;
  /**
   * Stock level (per product, or per size) at or below which it counts as low.
   */
  lowStockThreshold?: number | null;
  /**
   * Set automatically — prevents sending twice in the same day.
   */
  lowStockAlertLastSentAt?: string | null;
  /**
   * Toggle the bar on/off without losing the text.
   */
  announcementEnabled?: boolean | null;
  /**
   * e.g. "Free delivery on orders over $50" or "New drop live now →"
   */
  announcementText?: string | null;
  /**
   * Background hex color, e.g. #e8d5b0
   */
  announcementBgColor?: string | null;
  /**
   * Text hex color, e.g. #0a0a0a
   */
  announcementTextColor?: string | null;
  /**
   * Optional link — makes the whole bar clickable.
   */
  announcementHref?: string | null;
  footerTagline?: string | null;
  /**
   * Displayed in the bottom-right of the footer.
   */
  footerNote?: string | null;
  /**
   * Use {year} as a placeholder for the current year.
   */
  copyrightText?: string | null;
  /**
   * Social media icons shown in the footer.
   */
  socialLinks?:
    | {
        platform: 'instagram' | 'tiktok' | 'twitter' | 'facebook' | 'youtube';
        /**
         * Full URL including https://
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Font for headings / the logo wordmark.
   */
  headingFont?: ('system' | 'inter' | 'space-grotesk' | 'playfair' | 'dm-sans' | 'manrope') | null;
  /**
   * Font for body text and UI.
   */
  bodyFont?: ('system' | 'inter' | 'space-grotesk' | 'playfair' | 'dm-sans' | 'manrope') | null;
  /**
   * Corner style for cards, buttons, inputs, and images.
   */
  borderRadius?: ('sharp' | 'soft' | 'round') | null;
  /**
   * Choose a preset or select Custom to define every color individually.
   */
  colorScheme?: ('dark' | 'light' | 'warm' | 'custom') | null;
  /**
   * All fields accept hex values, e.g. #ffffff
   */
  customColors?: {
    /**
     * Page background
     */
    bg?: string | null;
    /**
     * Card / panel background
     */
    surface?: string | null;
    /**
     * Border and divider color
     */
    border?: string | null;
    /**
     * Primary text color
     */
    foreground?: string | null;
    /**
     * Secondary / muted text color
     */
    muted?: string | null;
    /**
     * Button and highlight color
     */
    accent?: string | null;
    /**
     * Button hover color
     */
    accentHover?: string | null;
    /**
     * Text color ON accent backgrounds (buttons, badges)
     */
    onAccent?: string | null;
  };
  metaDescription?: string | null;
  /**
   * Default social share image. Pick or upload (recommended 1200×630px). Fills the URL below.
   */
  ogImageMedia?: (number | null) | Media;
  /**
   * Auto-filled from the image above, or paste a Supabase Storage URL. Recommended: 1200×630px.
   */
  ogImage?: string | null;
  /**
   * Browser tab icon — square PNG/ICO/SVG. Pick or upload; fills the URL below.
   */
  faviconMedia?: (number | null) | Media;
  /**
   * Auto-filled from the icon above, or paste a Supabase Storage URL. Leave blank to use the Next.js default.
   */
  faviconUrl?: string | null;
  /**
   * Google Analytics 4 Measurement ID (e.g. G-XXXXXXXXXX). Leave blank to disable — the GA script only loads when set.
   */
  gaMeasurementId?: string | null;
  /**
   * Meta (Facebook) Pixel ID — numeric. Leave blank to disable — the Pixel script only loads when set.
   */
  metaPixelId?: string | null;
  /**
   * Short note shown under the details on every product page.
   */
  productBlurb?: string | null;
  /**
   * Filled into the {tagline} placeholder in the pattern below.
   */
  productMetaTagline?: string | null;
  /**
   * Product SEO/social description template. Placeholders: {store}, {title}, {tagline}. Translate the wording (not just the placeholders) for other locales — word order can differ.
   */
  productMetaPattern?: string | null;
  /**
   * Shown on the cart page when the cart is empty.
   */
  emptyCartMessage?: string | null;
  /**
   * Subtitle on the order-confirmation page after checkout.
   */
  orderThankYouNote?: string | null;
  /**
   * Opening line of the order-confirmation email (after "Hi {name},").
   */
  emailGreeting?: string | null;
  /**
   * Email footer tagline. Rendered as "{store name} — {this}". Leave the store name out; it is added automatically.
   */
  emailFooterNote?: string | null;
  /**
   * Prefix for generated order numbers, e.g. "TRK" → TRK-123456-AB12. Letters/numbers only; changing it does not rename existing orders.
   */
  orderNumberPrefix?: string | null;
  /**
   * Send a scheduled email digest of the reports below.
   */
  reportsEmailEnabled?: boolean | null;
  reportsEmailCadence?: ('weekly' | 'monthly') | null;
  /**
   * Comma-separated email addresses. Leave empty to use Contact Email (Brand tab).
   */
  reportsEmailRecipients?: string | null;
  sendSalesReport?: boolean | null;
  sendInventoryReport?: boolean | null;
  sendCustomersReport?: boolean | null;
  sendDiscountsReport?: boolean | null;
  sendPaymentsReport?: boolean | null;
  /**
   * Set automatically — prevents sending twice in the same period.
   */
  reportsEmailLastSentAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage header and footer navigation links without touching code.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Links shown in the top navigation bar. Order here = order on screen.
   */
  headerLinks?:
    | {
        label: string;
        /**
         * e.g. /shop  or  https://external-site.com
         */
        href: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Columns rendered in the footer. Each column has a title and its own list of links.
   */
  footerColumns?:
    | {
        /**
         * e.g. "Explore" or "Info"
         */
        columnTitle: string;
        links?:
          | {
              label: string;
              href: string;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Build the homepage by adding, reordering, and toggling sections. No code required.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * Drag to reorder. Click a section to expand and edit its fields.
   */
  sections?:
    | (
        | {
            /**
             * Small label above headline, e.g. "Lebanon · Hand-painted"
             */
            eyebrow?: string | null;
            headline?: string | null;
            subline?: string | null;
            /**
             * Primary button text, e.g. "Shop Now"
             */
            ctaLabel?: string | null;
            /**
             * Primary button link, e.g. /shop
             */
            ctaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            /**
             * Pick or upload a full-bleed background image. Fills the URL below.
             */
            bgImageMedia?: (number | null) | Media;
            /**
             * Auto-filled from the image above, or paste a Supabase Storage public URL.
             */
            bgImage?: string | null;
            /**
             * Hex background color, e.g. #0a0a0a (shown behind/instead of image)
             */
            bgColor?: string | null;
            /**
             * Black overlay over bg image 0–100 (use 30–60 to ensure text is readable)
             */
            overlayOpacity?: number | null;
            textAlign?: ('left' | 'center' | 'right') | null;
            minHeight?: ('50vh' | '70vh' | '80vh' | '100vh') | null;
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Each slide is a full-screen panel. Add at least one.
             */
            slides?:
              | {
                  /**
                   * Pick or upload a slide background. Fills the URL below.
                   */
                  bgImageMedia?: (number | null) | Media;
                  /**
                   * Auto-filled from the image above, or paste a Supabase Storage public URL.
                   */
                  bgImage?: string | null;
                  /**
                   * Hex fallback color shown behind/instead of image
                   */
                  bgColor?: string | null;
                  /**
                   * Black overlay 0–100 for text legibility
                   */
                  overlayOpacity?: number | null;
                  eyebrow?: string | null;
                  headline?: string | null;
                  subline?: string | null;
                  ctaLabel?: string | null;
                  ctaHref?: string | null;
                  id?: string | null;
                }[]
              | null;
            height?: ('60vh' | '70vh' | '80vh' | '100vh') | null;
            /**
             * Milliseconds between auto-advance (default: 5000 = 5s). Set to 0 to disable.
             */
            autoplayInterval?: number | null;
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'slideshow';
          }
        | {
            sectionTitle?: string | null;
            viewAllLabel?: string | null;
            viewAllHref?: string | null;
            source?: ('latest' | 'manual') | null;
            /**
             * How many products to show
             */
            limit?: number | null;
            /**
             * Pick the exact products to feature
             */
            products?: (number | Product)[] | null;
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featured-products';
          }
        | {
            /**
             * Pick or upload the section image. Fills the URL below.
             */
            imageMedia?: (number | null) | Media;
            /**
             * Auto-filled from the image above, or paste a Supabase Storage public URL.
             */
            image?: string | null;
            imageAlt?: string | null;
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            imagePosition?: ('left' | 'right') | null;
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-text';
          }
        | {
            /**
             * A single impactful sentence — displayed centered in large muted text.
             */
            text: string;
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statement';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text';
          }
        | {
            headline?: string | null;
            subline?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            /**
             * Pick or upload an optional full-bleed background. Fills the URL below.
             */
            bgImageMedia?: (number | null) | Media;
            /**
             * Auto-filled from the image above, or paste a Supabase Storage public URL.
             */
            bgImage?: string | null;
            /**
             * Hex background color, e.g. #e8d5b0. Defaults to accent color.
             */
            bgColor?: string | null;
            overlayOpacity?: number | null;
            /**
             * Hex text color. Defaults to on-accent (auto from theme).
             */
            textColor?: string | null;
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta-banner';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  storeName?: T;
  logo?: T;
  logoUrl?: T;
  tagline?: T;
  contactEmail?: T;
  whatsappNumber?: T;
  deliveryZones?:
    | T
    | {
        label?: T;
        fee?: T;
        id?: T;
      };
  freeDeliveryThreshold?: T;
  bankTransferInstructions?: T;
  cardPaymentsEnabled?: T;
  cardPaymentProvider?: T;
  omtPaymentEnabled?: T;
  omtInstructions?: T;
  currencyDisplayMode?: T;
  exchangeRate?: T;
  vatEnabled?: T;
  vatRate?: T;
  vatRegistrationNumber?: T;
  lowStockAlertEnabled?: T;
  lowStockThreshold?: T;
  lowStockAlertLastSentAt?: T;
  announcementEnabled?: T;
  announcementText?: T;
  announcementBgColor?: T;
  announcementTextColor?: T;
  announcementHref?: T;
  footerTagline?: T;
  footerNote?: T;
  copyrightText?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  headingFont?: T;
  bodyFont?: T;
  borderRadius?: T;
  colorScheme?: T;
  customColors?:
    | T
    | {
        bg?: T;
        surface?: T;
        border?: T;
        foreground?: T;
        muted?: T;
        accent?: T;
        accentHover?: T;
        onAccent?: T;
      };
  metaDescription?: T;
  ogImageMedia?: T;
  ogImage?: T;
  faviconMedia?: T;
  faviconUrl?: T;
  gaMeasurementId?: T;
  metaPixelId?: T;
  productBlurb?: T;
  productMetaTagline?: T;
  productMetaPattern?: T;
  emptyCartMessage?: T;
  orderThankYouNote?: T;
  emailGreeting?: T;
  emailFooterNote?: T;
  orderNumberPrefix?: T;
  reportsEmailEnabled?: T;
  reportsEmailCadence?: T;
  reportsEmailRecipients?: T;
  sendSalesReport?: T;
  sendInventoryReport?: T;
  sendCustomersReport?: T;
  sendDiscountsReport?: T;
  sendPaymentsReport?: T;
  reportsEmailLastSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  headerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        columnTitle?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subline?: T;
              ctaLabel?: T;
              ctaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              bgImageMedia?: T;
              bgImage?: T;
              bgColor?: T;
              overlayOpacity?: T;
              textAlign?: T;
              minHeight?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        slideshow?:
          | T
          | {
              slides?:
                | T
                | {
                    bgImageMedia?: T;
                    bgImage?: T;
                    bgColor?: T;
                    overlayOpacity?: T;
                    eyebrow?: T;
                    headline?: T;
                    subline?: T;
                    ctaLabel?: T;
                    ctaHref?: T;
                    id?: T;
                  };
              height?: T;
              autoplayInterval?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        'featured-products'?:
          | T
          | {
              sectionTitle?: T;
              viewAllLabel?: T;
              viewAllHref?: T;
              source?: T;
              limit?: T;
              products?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        'image-text'?:
          | T
          | {
              imageMedia?: T;
              image?: T;
              imageAlt?: T;
              eyebrow?: T;
              heading?: T;
              body?: T;
              ctaLabel?: T;
              ctaHref?: T;
              imagePosition?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        statement?:
          | T
          | {
              text?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              content?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        'cta-banner'?:
          | T
          | {
              headline?: T;
              subline?: T;
              ctaLabel?: T;
              ctaHref?: T;
              bgImageMedia?: T;
              bgImage?: T;
              bgColor?: T;
              overlayOpacity?: T;
              textColor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}